[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = false
gas_reports = ["SecureVault"]

[profile.ci]
verbosity = 4
optimizer_runs = 999999

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
